install.packages("data.table",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("optparse",repos= "http://lib.stat.cmu.edu/R/CRAN/")
install.packages("ggplot2")
install.packages("devtools")
install.packages("rstudioapi", dependencies = TRUE, repos="http://cran.rstudio.com")
install.packages("rvest")
install.packages("httr")
install.packages("readxl")
install.packages("janitor")
install.packages("glue")
install.packages("Hmisc")
install.packages("tidyverse")
devtools::install_github(repo = "FantasyFootballAnalytics/ffanalytics", build_vignettes = TRUE)
install.packages("XML")
